name: Deploy to PROD on uat branch push

on:
  push:
    branches:
      - 'uat'        # â† Yahan 'uat' rakho, 'main' nahi
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-sffnoobs-environment:
    runs-on: ubuntu-latest
    environment: sffnoobs

    steps:
       - uses: actions/setup-node@v3
         with:
          node-version: '18'

       - name: Checkout source code
         uses: actions/checkout@v3
         with:
          fetch-depth: 2

       - name: Install Salesforce CLI
         run: npm install @salesforce/cli --global

       - name: Install sfdx git delta
         run: echo Y | sf plugins install sfdx-git-delta

       - name: Login to UAT Org
         run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt \
            --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default

       - name: Create delta packages
         run: |
          mkdir changed-sources
          sf sgd source delta \
            --to "HEAD" \
            --from "HEAD~1" \
            --output changed-sources/ \
            --generate-delta \
            --source force-app/

       - name: Validate Deployment
         run: |
          sf project deploy start \
            --source-dir changed-sources/force-app \
            --test-level RunLocalTests \
            --dry-run

       - name: Deploy to UAT
         run: |
          sf project deploy start \
            --source-dir changed-sources/force-app \
            --test-level RunLocalTests
